### ISSUE TITLE
[NOT AN ISSUE] Simple questions

### ISSUE THREAD

**Issue by EstherMoellman** [adio93/YT-Auto-Dark-Mode#1]
Hi @adio93 !

Firstly, thank you for YT-Auto-dark-Mode... what a gem! Congratulations! Please if possible, I have few questions:

1) I would like to have YT in full-time dark theme, 24 hours per day. But I don't have JS' knowledge. Please, what I need to change in your JS' script in order to have a full-time YT dark theme?

2) When YT loads, the first seconds is in white theme, and only after that it becomes dark theme. Please, what I need to do in order to have the YT dark theme directly (no white theme at all)?
PS: I tried "@run-at  document-start" but it didn't worked.

Thank you in advance! : )

**Comment by adio93** [comment]
Hi,

Ad.1 for this you need only this line 
document.getElementsByTagName('html')[0].setAttribute('dark', 'true');
but to do this you can set it up permanently in youtube itself. 

Ad.2 This delay is because YT firstly must be loaded to change attributes but I will try to improve it.

Thanks for your feedback.

**Comment by EstherMoellman** [comment]
Thank you for your replay. I'm closing the issue, but please allow me the last two questions:

Ad.1 Sorry my JS' ignorance, but what exactly do you mean by "only need"? I deleted "else { document.getElementsByTagName('html')[0].removeAttribute('dark'); }" and it worked. Is it that what you meant? Or may I delete more lines?

Ad.2  The white-theme in the first loading seconds is quiet annoying, almost kills the whole automatic dark theme experience. So, really, it'll be fantastic if you can remove this horrible white theme. In this context, if you allow me, please I'll open a separate specific issue here in your GitHub.

Once again, tons of thanks!
